install: 
        - wget http://apt.biicode.com/install.sh && chmod +x install.sh && ./install.sh 
        - bii setup:cpp
        - bii --version
language: cpp

compiler:
        - clang
        - gcc

before_script:
        bii configure

script: bii build
